Traceback (most recent call last):
  File "run_network.py", line 172, in <module>
    train_model()
  File "run_network.py", line 153, in train_model
    train(model, train_loader, eval_loader, args.epochs, optimizer, args, epoch, best_val_score, best_epoch)
  File "/hdd/robik/projects/ramen/train.py", line 97, in train
    loss.backward()
  File "/home/robik/anaconda/envs/vqa2/lib/python3.6/site-packages/torch/tensor.py", line 102, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/home/robik/anaconda/envs/vqa2/lib/python3.6/site-packages/torch/autograd/__init__.py", line 90, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: select(): index 14 out of range for tensor of size [14, 64, 300] at dimension 0
